pub mod approve_market;
pub mod claim_reward;
pub mod dimiss_market;
pub mod initialize_platform;
pub mod place_prediction;
pub mod propose_market;
pub mod resolve_market;
pub mod update_market_config;
pub mod update_platform_config;

pub use approve_market::*;
pub use claim_reward::*;
pub use dimiss_market::*;
pub use initialize_platform::*;
pub use place_prediction::*;
pub use propose_market::*;
pub use resolve_market::*;
pub use update_market_config::*;
pub use update_platform_config::*;
